# A Kernel of Health {#kernel-of-health}

#### Keywords

Disease; ailment; health condition; diagnosis; etiology; unknown cause; idiopathic; confounding variables; nostrum; pseudoscience; quackery; crowdsource; research; remedy

## Health confounded

They say that in every lie there’s a kernel of truth. There are a multitude of health conditions for which no cure has been discovered, and this is often due at least in part to there being no known cause. The efficiency of medical research is constrained by our limited ability to conduct human subjects testing, often forcing us to rely on observational studies in lieu of controlled experiments, and leaving us with insufficient capacity to investigate all of the various maladies in existence. Lacking satisfactory solutions from the medical profession, many turn to the Internet of desperation, in spite of it being notoriously riddled with pseudoscience and potentially harmful misinformation [1]. Even if a condition has been accurately diagnosed, sham treatments can fail to improve health -— or perhaps make it worse [2].

## Light at the end of the tunnel

Crowdsourcing seems to be in the trough of its hype cycle, but patients often have novel (ahem) hypotheses regarding possible etiology of their ailment, and why not harness this energy? What if we could create a network, moderated by their doctors, for patients who share a single accurate diagnosis? Imagine providing an environment for them to brainstorm together, where they could offer and compare ideas for all sorts of potential causes, ranging from deodorant ingredients to nervous habits? Sure, most of the data would probably be a little wide of the mark, and some commonalities would be no less prevalent in the rest of the population. But even if only one in ten such networks leads to a new and efficacious remedy, wouldn’t this justify panning for a little gold? 

Fortunately, the solution is already here, embodied in the Kernel of Health patient-centric system. To ensure network quality, participant admittance and retention in the system is controlled by the doctors responsible for their diagnosis. Participants are only identifiable by their doctors, and provide consent after being fully informed regarding the allowed usage of their submitted data. They're encouraged to create (and upvote) new variables, however nonsensical they might be, and the system distributes these new variables to other participants to upvote in turn. 

All participants have skin in the game, so to speak, so engagement is robust. And although patients inevitably bring their own biases to the system, two safeguards have been put in place to ensure the system does not worsen the confusion. First, patients must submit a set of initial hypotheses before gaining access to the hypotheses of other participants. Second, rather than being allowed a full view of the hypothesis population, each participant is presented with a random sample of equally-weighted hypotheses before being allowed to submit additional hypotheses of their own (perhaps inspired by their view of the sample). 

## Out of the darkness

With just one year under its belt, the Kernel of Health system has already identified likely culprits for several idiopathic health conditions, and research aimed at vetting these promising new leads is underway. Although the potential value of this dataset for other applications is not lost on corporations, the safeguards that were initially put in place have been preserved and reinforced over time to ensure that participant privacy remains intact. Even for participants whose conditions remain without known cause, salubrious engagement with doctors is enhanced, and reliance on Internet quackery and nostrums is reduced -— all to the benefit of the patients and science.

## References

[1] http://www.latimes.com/business/hiltzik/la-fi-mh-reporting-on-quacks-and-pseudoscience-20150413-column.html
[2] http://www.npr.org/sections/thetwo-way/2016/05/03/476673789/china-investigates-search-engine-baidu-after-student-dies-of-cancer
