# A Speaker for Crows {#speaker-for-the-crows}

## Keywords

crow; raven; corvid; intelligence; communication; language; converse; machine learning; 

## Bright minds shrouded in darkness

Growing up in the country, I was taught that a helpless bird on the ground was as good as dead. So when I found a young crow one day in my backyard I promptly dispatched it, thinking this was a mercy. A year later, its friends and family clearly still hadn't forgiven me [1,2]. Several years later, I watched "A Murder of Crows" on PBS and finally understood the gravity of my crime [3]. Although I eventually served my penance in their minds, my interest in corvids and other intelligent wild birds has since only grown. 

Crows fortunately tend to thrive in the presence of humans, and their brainpower isn't lost on the data science community [4,5]. Machine-learning has been applied to crowdsourced data to study migration patterns [6], but prior to our work, data science had not been used for bird identification. We recognized that if birds could be identified by their distinctive vocal signatures, this could save substantial time for ornithologists while also reducing the stress for birds associated with tagging. 

## Many birds, one Rosetta stone

American crows express themselves in subsong (albeit rather obnoxiously to most human ears), and are known to use over 20 different calls [7]. Subtle differences between vocal signatures were believed to identify individuals, and dialects distinguish groups [8]. Software was already available to analyze crow calls [9], and earbuds capable of real-time human language translation were recently introduced [10]. Provided a large body of data for a set of tagged birds, we employed supervised machine learning, trained to recognize the following: call meaning/type, call source (i.e., individual), and source grouping (e.g., dialect, age, sex).

We then produced a beta version of our CrowSpeak smartphone app for use by ornithologists, who are already proving to be enthusiastic adopters of this bird identification tool, while also informing its ongoing development. Once ready, the first public release will be used to enlist the help of birdwatchers around the country, thereby greatly diversifying the dataset. We will soon have enough data to further isolate features of vocal signatures that may further improve accuracy by recognizing factors such as demeanor and social status. It is already clear that tagging can in the near future be obviated entirely. 

## We were promised Darwins

We have not yet established a robust means of conversing with crows or any other intelligent non-human species on its own terms. And maybe that's for the better -- perhaps we'd only learn that, in addition to sounding obnoxious, they're really only interested in yelling at us to give them a peanut [11]. Indeed, work on communicating with other species has recently met with justified skepticism [12]. But scientific discoveries are often (if not by definition) surprising, and for the time being, the potential benefits (for humans and non-humans alike) of inter-species communication can only be guessed at. In the interim, the ability to identify birds by their calls is empowering, and the prospect of soon understanding their language is thrilling. 

## References

[1] http://www.nytimes.com/2008/08/26/science/26crow.html  
[2] http://www.audubon.org/magazine/march-april-2016/meet-bird-brainiacs-american-crow  
[3] http://www.pbs.org/wnet/nature/a-murder-of-crows-crow-facts/5965/  
[4] https://www.cs.princeton.edu/courses/archive/fall16/cos402/lectures/402-lec1.pdf  
[5] http://www.birds.cornell.edu/brp/modeling/  
[6] https://research.cornell.edu/news-features/statistics-machine-learning-uncertainty  
[7] https://www.allaboutbirds.org/guide/American_Crow/sounds  
[8] http://news.cornell.edu/stories/2007/02/analysis-shows-differences-alarm-calls-individual-crows  
[9] http://www.birds.cornell.edu/brp/raven/RavenOverview.html  
[10] https://arstechnica.com/gadgets/2017/10/google-pixel-buds-are-wireless-earbuds-that-translate-conversations-in-real-time/  
[11] https://io9.gizmodo.com/heres-what-crows-and-ravens-are-really-saying-1649142811  
[12] http://www.slate.com/articles/health_and_science/science/2014/08/koko_kanzi_and_ape_language_research_criticism_of_working_conditions_and.html
